# Setup
title:        vkein it blog
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      "https://jaeheehan.github.io"
paginate:     1
locale:       "ko"

# About/contact
author:
  name:       vkein
  url:        https://jaeheehan.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: vkein
